### ISSUE TITLE
Do we need coding guidelines?

### ISSUE THREAD

**Issue by olgierd-on-fire** [Aliin/Symposium#13]
I found [PSR-1](http://www.php-fig.org/psr/psr-1/) and [PSR-2](http://www.php-fig.org/psr/psr-2/).
These are recommendations from PHP-FIG group.

**Comment by Mortiferr** [comment]
I like those a lot.

**Comment by Aliin** [comment]
I agree, they look good. A lot of suggestions that just make sense and are used often anyway, otherwise I like the demand to put everything in classes or functions, no standalone code via require. I'm gonna have to learn how to use namespaces correctly but I want to learn from this after all :D xD So I'm gonna put the PSR in the readme if nobody complains.

**Comment by Aliin** [comment]
Thanks olgierd, great Thing.
