### ISSUE TITLE
Receiving syntax error after Database setup 

### ISSUE THREAD

**Issue by Mortiferr** [Aliin/Symposium#38]
`Parse error: syntax error, unexpected 'return' (T_RETURN) in C:\xampp\htdocs\database\posts.php on line 18`

**Comment by Mortiferr** [comment]
```
$query = 

return $cat_array;
```

`return $cat_array;`

is the 18th line but I thought I would include the one above it.

**Comment by Aliin** [comment]
Ahm yes. Which branch are you trying to run? To solve the Problem I updated the frontend branch to the newest dev Version from display-Posts. Anyway, I think the Problem is that I'm not using Posts.php anymore right now, it's broken until I Change it. The index.php file actually refers to the file categories.php in the database Folder (makes more sense). So it should work now if you're trying to run the frontend branch.

**Comment by Aliin** [comment]
Maybe there's a Problem with master I will fix it when I finished the diplay-posts branch by just pulling it to master.

**Comment by Aliin** [comment]
I fixed the master. But I mean the Problem with the master after all was that there was just no working Version yet, that's why I want to finish a v0.1.0 quickly. Right now, even if in heavy development, Display-Posts works best, so I suggest I pull it onto master already? What do you think? Even if the top of file comments and everything are wrong still...
Well I might just make a pull request and fix the code and everything today so we can push it to master before I continue coding.
